//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loltimer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("loltimer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream darke1min {
            get {
                return ResourceManager.GetStream("darke1min", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream drake30sec {
            get {
                return ResourceManager.GetStream("drake30sec", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream drakespawned {
            get {
                return ResourceManager.GetStream("drakespawned", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon lol {
            get {
                object obj = ResourceManager.GetObject("lol", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Loopo_a {
            get {
                return ResourceManager.GetStream("Loopo_a", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Loopo_b {
            get {
                return ResourceManager.GetStream("Loopo_b", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream nashor1min {
            get {
                return ResourceManager.GetStream("nashor1min", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream nashor30sec {
            get {
                return ResourceManager.GetStream("nashor30sec", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream nashorspawned {
            get {
                return ResourceManager.GetStream("nashorspawned", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ourblue1min {
            get {
                return ResourceManager.GetStream("ourblue1min", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ourblue30sec {
            get {
                return ResourceManager.GetStream("ourblue30sec", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ourbluespawned {
            get {
                return ResourceManager.GetStream("ourbluespawned", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream oured30sec {
            get {
                return ResourceManager.GetStream("oured30sec", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ourred1min {
            get {
                return ResourceManager.GetStream("ourred1min", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ourredspawned {
            get {
                return ResourceManager.GetStream("ourredspawned", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream theirblue1min {
            get {
                return ResourceManager.GetStream("theirblue1min", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream theirblue30sec {
            get {
                return ResourceManager.GetStream("theirblue30sec", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream theirbluespawned {
            get {
                return ResourceManager.GetStream("theirbluespawned", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream theirred1min {
            get {
                return ResourceManager.GetStream("theirred1min", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream theirred30sec {
            get {
                return ResourceManager.GetStream("theirred30sec", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream theirredspawned {
            get {
                return ResourceManager.GetStream("theirredspawned", resourceCulture);
            }
        }
    }
}
